<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="login_functionality_test"
    errors="1" failures="0" hostname="" id="" package="login_functionality_test" skipped="0"
    tests="1" time="0.005000" timestamp="Thu, 29 Nov 2018 15:34:27 GMT">
  
    <testcase name="Login with valid credentials" classname="login_functionality_test" time="0.005000" assertions="0">
    </testcase>
  

  
    <system-err>
        Error while running [Login Functionality Test / Login with valid credentials]:

  TypeError: loginPage.gotoSite is not a function
    at Object.Login with valid credentials (C:\Users\v-midhun.gaddipati\Documents\Nightwatch automation\nightwatch-poc\tests\e2e\login_functionality_test.js:7:19)
    at Module.call (C:\Users\v-midhun.gaddipati\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\module.js:62:34)
    at C:\Users\v-midhun.gaddipati\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (C:\Users\v-midhun.gaddipati\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\v-midhun.gaddipati\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\v-midhun.gaddipati\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:796:13)
    at C:\Users\v-midhun.gaddipati\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:556:49
    at runSingle (C:\Users\v-midhun.gaddipati\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:137:13)
    at flush (C:\Users\v-midhun.gaddipati\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    </system-err>
  

  
  </testsuite>
</testsuites>
